### ISSUE TITLE
hidden elements inside <paper-item> cause misaligned margins

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-item#30]
paper-item-shared-styles.html applies a `margin-right` of `16-px` to all middle content items:
```
      :host > ::content > *:not(:first-child):not(:last-child) {
        margin-right: 16px;
      }
```

This is weird because the first or last item may be conditionally hidden, causing there to be a 16-px margin between the last *visible* item and the right border of the paper-item.

http://jsfiddle.net/8rkvb5jf/

Can we come up with a better way to provide this spacing?

**Comment by notwaldorf** [comment]
@mgiuffrida I think this is no longer the case (i don't see that style in `paper-item` nor `paper-menu`), and this is what your fiddle looks like:
<img width="296" alt="screen shot 2015-10-26 at 11 35 21 am" src="https://cloud.githubusercontent.com/assets/1369170/10738678/b139fc76-7bd5-11e5-9e3f-fa88c65946c3.png">

Is this what the expected behaviour is?

**Comment by mgiuffrida** [comment]
Yes it looks like @cdata removed the margin entirely in #32.
