### ISSUE TITLE
Apply ripple to paper-item and paper-icon-item

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/paper-item#43]
Today, tapping a `paper-item` or `paper-icon-item` directly flips the background color to grey.
It would be more natural if tapping a `paper-item` would play the ripple animation.

See https://github.com/PolymerElements/paper-behaviors/blob/master/paper-ripple-behavior.html

**Comment by notwaldorf** [comment]
Here is an example of how you can apply the ripple yourself, on demand: http://jsbin.com/debevi/edit?html

I think `paper-item` is meant to be a fairly simple and inexpensive element, that can be easily used in lists and menus. Adding a ripple by default means making the element heavier, and also means that all of those elements (`paper-menu`, `paper-dropdown-menu`) would have to explicitly remove it, since it goes against the spec.

**Comment by ronnyroeller** [comment]
Thanks for your response @notwaldorf 
Just for reference: The advantage of PaperRippleBehavior is that it creates the <paper-ripple> node only on demand thereby making the ripple-enabled element lighter.

**Comment by jscissr** [comment]
> [...] all of those elements (`paper-menu`, `paper-dropdown-menu`) would have to explicitly remove it, since it goes against the spec.

Are you sure about that @notwaldorf ?
I actually do see ripples in drop-down  in [the spec](https://www.google.com/design/spec/components/menus.html) (in the animations).

**Comment by ronnyroeller** [comment]
@notwaldorf - I just saw your talk on Google IO where you mentioned using the `PaperRippleBehavior` instead of `paper-ripple` element (https://www.youtube.com/watch?v=zfQoleQEa4w). Do you have any advice how to use `PaperRippleBehavior` for `paper-item`?
Our use case: We use `paper-item` in most of our listers and need to provide visual feedback when the user touched them.

**Comment by notwaldorf** [comment]
@ronnyroeller In particular for `paper-item` we will probably not add it to the element itself, since the element is a bit of an anti-pattern (it's basically a button with styles). However, if you wanted to make your own element that is similar to `paper-item`, you could look at what `paper-checkbox` does; in particular, it uses `PaperInkyFocusBehavior`, which uses the `PaperRippleBehavior` here: https://github.com/PolymerElements/paper-behaviors/blob/master/paper-inky-focus-behavior.html
